import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { signUpSchema, ISignUp } from "../../server/validations/auth";
import { trpc } from "../../utils/trpc";
import Layout from "../../components/layout/layout";
import UserSignup from "../../components/userSignup/userSignup";

const SignUp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Workout App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activePage='Back to First page' justHeader>
        <UserSignup />
      </Layout>
    </div>
  );
};

export default SignUp;
