import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";
import Layout from "../components/layout/layout";
import UserLogin from "../components/userLogin/userLogin";
import { useRouter } from "next/router";


const Home: NextPage = () => {
  const router = useRouter()
  const {data: session} = useSession()

  useEffect(() => {
    if(session) {
      router.push('/dashboard/user')
    }
  }, [session, router])

  return (
    <>
      <Head>
        <title>Workout app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout activePage='Back to First page' justHeader>
        <UserLogin />
      </Layout>
    </>
  )

};

export default Home;
