import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { emptyAthlete, useUserStore } from '../stores/userStore'
import styles from '../styles/Home.module.scss'
import { handleLogin } from '../utils/strava'


const Home: NextPage = () => {
  const { athlete, setAthlete } = useUserStore()
  return (
    <div className={styles.container}>
      <Head>
        <title>Strava Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!athlete && <button onClick={handleLogin}>Connect to strava</button>}
      {athlete && (
        <>
          <Link href='/user'>Go to Stats Page</Link>
          <button onClick={() => setAthlete(emptyAthlete)}>Logout</button>
        </>
      )}

    </div>
  )
}

export default Home
