import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { emptyAthlete, useUserStore } from '../stores/userStore'
import styles from '../styles/Home.module.scss'
import { handleLogin } from '../utils/strava'
import { trpc } from '../utils/trpc'


const Home: NextPage = (props: any) => {
  const {data, isLoading} = trpc.useQuery(['goals.get-all'])
  const { mutate } =  trpc.useMutation('goals.create')
  const createGoal = () => {
    mutate({ name: 'New Goal' })
  }
  console.log('db goals', data)
  const { athlete, setAthlete } = useUserStore()
  return (
    <div className={styles.container}>
      <Head>
        <title>Strava Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {!athlete.id && <button onClick={handleLogin}>Connect to strava</button>}
        {!!athlete.id &&
          <>
            <Link href='/user'>Go to Stats Page</Link>
            <button onClick={() => setAthlete(emptyAthlete)}>Logout</button>
          </>
        }
        <code>{props.goals}</code>
        <button onClick={() => createGoal()}>new</button>
      </>
    </div>
  )
}

export default Home
